name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install ajv-cli + formats
        run: npm install -g ajv-cli ajv-formats

      - name: Validate minimum fixture against schema
        run: |
          ajv -c ajv-formats validate \
            -s schema/v1.4.2.json \
            -d fixtures/minimum.json

  swift-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build Swift project (macOS)
        run: xcodebuild build -scheme Compass -destination 'platform=macOS' CODE_SIGNING_ALLOWED=NO

  swift-tests:
    runs-on: macos-latest
    needs: swift-build
    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Run Swift tests (macOS)
        run: xcodebuild test -scheme Compass -destination 'platform=macOS' CODE_SIGNING_ALLOWED=NO
