name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install ajv-cli
        run: npm install -g ajv-cli
      - name: Validate fixtures against schema
        run: |
          ajv validate -s schema/v1.4.2.json -d fixtures/mini.json

  swift-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      - name: Run Swift tests
        run: xcodebuild test \
          -scheme Compass \
          -destination 'platform=iOS Simulator,name=iPhone 14'
